packages:
    - 'packages/*'

onlyBuiltDependencies:
    - '@swc/core'
    - bufferutil
    - canvas
    - core-js
    - core-js-pure
    - esbuild
    - faiss-node
    - msgpackr-extract
    - protobufjs
    - sharp
    - sqlite3
    - ssh2
    - utf-8-validate

overrides:
    axios: 1.15.0
    body-parser: 2.0.2
    braces: 3.0.3
    cross-spawn: 7.0.6
    form-data: 4.0.4
    glob-parent: 6.0.2
    http-proxy-middleware: 3.0.3
    json5: 2.2.3
    nth-check: 2.1.1
    path-to-regexp: 0.1.12
    prismjs: 1.29.0
    rollup: 4.45.0
    semver: 7.7.1
    set-value: 4.1.0
    solid-js: 1.9.7
    tar-fs: 3.1.0
    unset-value: 2.0.1
    webpack-dev-middleware: 7.4.2
    ws: 8.18.3
    xlsx: 0.18.5
    uuid: ^10.0.0
